### ISSUE TITLE
Inference with more images

### ISSUE THREAD

**Issue by QitaoZhao** [hwjiang1510/LEAP#10]
Hi Hanwen,

Thanks for your interesting work! Does LEAP support inference with more than 5 images? (e.g., 6 or 8) If so should I just adjust the `num_frame` in the config file? 

Thanks!

**Comment by hwjiang1510** [comment]
Hi Qitao,

Yes, but be careful of OOM if you are using very dense views.

**Comment by QitaoZhao** [comment]
Thanks for your reply! Works nicely with 6 images!
