### ISSUE TITLE
novel view synthesis (random pose)

### ISSUE THREAD

**Issue by csy2077** [hwjiang1510/LEAP#11]
Hi, I appreciate your good work!

And I have some questions about the novel view image synthesis, I look through your code and I wonder whether LEAP can produce randomly given view images. It seems that it can only produce the 'target' view images noticed in your paper.

If it can , where can I change the view parameters to produce the wanted new view images?

**Comment by hwjiang1510** [comment]
Hi,

Thanks for your interest in our work.
Yes, it can produce novel views under any given camera pose. Please check [this function](https://github.com/hwjiang1510/LEAP/blob/2d0bf8d6b1be56bbae6d62423a77b967b91b1d68/scripts/demo.py#L40https://github.com/hwjiang1510/LEAP/blob/2d0bf8d6b1be56bbae6d62423a77b967b91b1d68/scripts/demo.py#L40) for details. In this function, I pre-define some elevation and azimuth pose to render 360-degree rotation. You can just modify it to any pose you want.

**Comment by csy2077** [comment]
Thanks for your early reply and it really helps!
