### ISSUE TITLE
Question regarding output

### ISSUE THREAD

**Issue by jclarkk** [hwjiang1510/LEAP#2]
Hi
Great work on this amazing project.

Would it be possible to output a mesh/point cloud via PLY or OBJ formats?

Thanks!

**Comment by hwjiang1510** [comment]
Thanks for your interest in our work!

The output of our model is a neural radiance field and we haven't implemented the function for converting it to mesh/point cloud. One straightforward method is to densely sample 3D points and get their density values. Then you can threshold the values to get the point cloud, or use the marching cube algorithm to get the mesh.
